#!/bin/bash
# write git information into plain files to reduce amount to reduce same bash scripting again and again

set -e
GIT_META_DIRECTORY=".git-meta"

if [ -z "${DLM_ENDPOINT+x}" ]; then
	echo "You have to provide the \$DLM_ENDPOINT variable. Which has to point to https://your-server/wp-json/download-monitor-release-version/v1/downloads/\${YOUR_ID}/release"
	exit 1
fi

GIT_META_VERSION_FILE="${GIT_META_DIRECTORY}/version"
if [ ! -e "$GIT_META_VERSION_FILE" ]; then
	echo "There is no ${GIT_META_VERSION_FILE} file available. Let the meta information be generated by using schakko/actions/git-meta."
	exit 1
fi

VERSION=`cat $GIT_META_VERSION_FILE`

# extract source URL for artifact
if [ -z "${ARTIFACT_URL_SOURCE_FILE+x}" ]; then
	URL_ATTRIBUTE=""
else
	URL_CONTENT=`cat ${ARTIFACT_URL_SOURCE_FILE}`
	URL_ATTRIBUTE=", \"url\": \"${URL_CONTENT}\""
fi

# extract meta information; this must be provided as a valid JSON object
if [ -z "${ARTIFACT_META_SOURCE_FILE+x}" ]; then
	META_ATTRIBUTE=""
else
	META_CONTENT=`cat ${ARTIFACT_META_SOURCE_FILE}`
	META_ATTRIBUTE=", \"meta\": ${META_CONTENT}"
fi

CREDENTIALS_BASE64=`echo "$USERNAME:$PASSWORD" | base64`

cat >release.json <<EOL
{
	"version": "$VERSION"
	${URL_ATTRIBUTE}
	${META_ATTRIBUTE}
}
EOL

curl -v --fail --insecure -XPOST -H "Content-type: application/json" -H "Authorization: Basic $BASE64" -d "@release.json" "$DLM_ENDPOINT"